version: '3'
services:
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SocialHighload
    ports:
    - "33060:3306"
      
  web:
    image: "aprikot/social-highload:latest"
    restart: always
    ports:
      - 8080:80
    links: 
      - "mysql:mysql"
    depends_on: 
      - mysql