version: '3'
services:
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SocialHighload
    ports:
    - "33061:3306"
      
  web:
    image: "aprikot/social-highload:1.0"
    restart: always
    ports:
      - 8081:80
    links: 
      - "mysql:mysql"
    depends_on: 
      - mysql
